In [2]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, roc_auc_score, classification_report

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_parquet("/Users/bennyschellinger/Desktop/DataScience/MLE_DataScientest/04_Projekt/MAY24_BDS_INT_Fire_Brigade/data/df_cleaned_for_classification_models.parquet")
df.head() 

IncidentGroup_Fire  IncidentGroup_Special Service  \
IncidentNumber                                                      
235138081                        0                              1   
2091                             1                              0   
3091                             1                              0   
5091                             1                              0   
6091                             0                              0   

                AggregatedPropertyCategory_Outdoor  \
IncidentNumber                                       
235138081                                        0   
2091                                             1   
3091                                             1   
5091                                             1   
6091                                             0   

                AggregatedPropertyCategory_Residential  \
IncidentNumber                                           
235138081                                            0   
2091                                                 0   
3091                                                 0   
5091                                                 0   
6091                                                 1   

                AggregatedPropertyCategory_Vehicle  \
IncidentNumber                                       
235138081                                        1   
2091                                             0   
3091                                             0   
5091                                             0   
6091                                             0   

                CellEastingNorthing2500_502500-175000  \
IncidentNumber                                          
235138081                                           0   
2091                                                0   
3091                                                0   
5091                                                0   
6091                                                0   

                CellEastingNorthing2500_502500-177500  \
IncidentNumber                                          
235138081                                           0   
2091                                                0   
3091                                                0   
5091                                                0   
6091                                                0   

                CellEastingNorthing2500_502500-180000  \
IncidentNumber                                          
235138081                                           0   
2091                                                0   
3091                                                0   
5091                                                0   
6091                                                0   

                CellEastingNorthing2500_502500-182500  \
IncidentNumber                                          
235138081                                           0   
2091                                                0   
3091                                                0   
5091                                                0   
6091                                                0   

                CellEastingNorthing2500_502500-187500  \
IncidentNumber                                          
235138081                                           0   
2091                                                0   
3091                                                0   
5091                                                0   
6091                                                0   

                CellEastingNorthing2500_502500-190000  \
IncidentNumber                                          
235138081                                           0   
2091                                                0   
3091                                                0   
5091                                                0   
6091                     

In [4]:
df.columns

Index(['IncidentGroup_Fire', 'IncidentGroup_Special Service',
       'AggregatedPropertyCategory_Outdoor',
       'AggregatedPropertyCategory_Residential',
       'AggregatedPropertyCategory_Vehicle',
       'CellEastingNorthing2500_502500-175000',
       'CellEastingNorthing2500_502500-177500',
       'CellEastingNorthing2500_502500-180000',
       'CellEastingNorthing2500_502500-182500',
       'CellEastingNorthing2500_502500-187500',
       ...
       'IsBankholiday', 'IsWeekend', 'DistanceStationLog', 'Hour_sin',
       'Hour_cos', 'Weekday_sin', 'Weekday_cos', 'Month_sin', 'Month_cos',
       'ResponseTimeBinary'],
      dtype='object', length=320)

# Model Training & Evaluation

In [5]:
X = df.drop("ResponseTimeBinary", axis = 1)
y = df["ResponseTimeBinary"]


In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 666)


### Decision Tree

In [8]:
decision_tree = DecisionTreeClassifier()
decision_tree.fit(X_train, y_train)

DecisionTreeClassifier()

In [9]:
y_train_pred_dt = decision_tree.predict(X_train)
y_test_pred_dt = decision_tree.predict(X_test)

### Random Forest

In [ ]:
random_forest = RandomForestClassifier()
random_forest.fit(X_train, y_train)


In [11]:
y_train_pred_rf = random_forest.predict(X_train)
y_test_pred_rf = random_forest.predict(X_test)

# Model Evaluation

### Decision Tree

#### Evaluation Decision Tree (Training Data)

In [12]:
print("Decision Tree - Training Data")
print("Accuracy:", accuracy_score(y_train, y_train_pred_dt))
print("Precision:", precision_score(y_train, y_train_pred_dt, average='binary'))
print("Recall:", recall_score(y_train, y_train_pred_dt, average='binary'))
print("F1 Score:", f1_score(y_train, y_train_pred_dt, average='binary'))
print("Confusion Matrix:\n", confusion_matrix(y_train, y_train_pred_dt))
print("ROC AUC Score:", roc_auc_score(y_train, y_train_pred_dt))
print("Classification Report:\n", classification_report(y_train, y_train_pred_dt))


Decision Tree - Training Data
Accuracy: 0.9967451467813615
Precision: 0.999768814190185
Recall: 0.9956210883045992
F1 Score: 0.9976906404031805
Confusion Matrix:
 [[361254    200]
 [  3804 864905]]
ROC AUC Score: 0.9975338837750454
Classification Report:
               precision    recall  f1-score   support

           0       0.99      1.00      0.99    361454
           1       1.00      1.00      1.00    868709

    accuracy                           1.00   1230163
   macro avg       0.99      1.00      1.00   1230163
weighted avg       1.00      1.00      1.00   1230163



#### Evaluation Decision Tree (Test Data)

In [13]:
print("\nDecision Tree - Test Data")
print("Accuracy:", accuracy_score(y_test, y_test_pred_dt))
print("Precision:", precision_score(y_test, y_test_pred_dt, average='binary'))
print("Recall:", recall_score(y_test, y_test_pred_dt, average='binary'))
print("F1 Score:", f1_score(y_test, y_test_pred_dt, average='binary'))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_test_pred_dt))
print("ROC AUC Score:", roc_auc_score(y_test, y_test_pred_dt))
print("Classification Report:\n", classification_report(y_test, y_test_pred_dt))



Decision Tree - Test Data
Accuracy: 0.6735362114319716
Precision: 0.7667334468139481
Recall: 0.773187051882668
F1 Score: 0.7699467262416223
Confusion Matrix:
 [[ 39128  51115]
 [ 49286 168012]]
ROC AUC Score: 0.6033859641359862
Classification Report:
               precision    recall  f1-score   support

           0       0.44      0.43      0.44     90243
           1       0.77      0.77      0.77    217298

    accuracy                           0.67    307541
   macro avg       0.60      0.60      0.60    307541
weighted avg       0.67      0.67      0.67    307541



### Random Forest

#### Evaluation Decision Tree (Training Data)

In [14]:
print("\nRandom Forest - Training Data")
print("Accuracy:", accuracy_score(y_train, y_train_pred_rf))
print("Precision:", precision_score(y_train, y_train_pred_rf, average='binary'))
print("Recall:", recall_score(y_train, y_train_pred_rf, average='binary'))
print("F1 Score:", f1_score(y_train, y_train_pred_rf, average='binary'))
print("Confusion Matrix:\n", confusion_matrix(y_train, y_train_pred_rf))
print("ROC AUC Score:", roc_auc_score(y_train, y_train_pred_rf))
print("Classification Report:\n", classification_report(y_train, y_train_pred_rf))



Random Forest - Training Data
Accuracy: 0.9967199468688296
Precision: 0.9965726440948174
Recall: 0.9987901587297933
F1 Score: 0.9976801692125397
Confusion Matrix:
 [[358470   2984]
 [  1051 867658]]
ROC AUC Score: 0.9952673065362657
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.99      0.99    361454
           1       1.00      1.00      1.00    868709

    accuracy                           1.00   1230163
   macro avg       1.00      1.00      1.00   1230163
weighted avg       1.00      1.00      1.00   1230163



#### Evaluation Decision Tree (Test Data)

In [15]:
print("\nRandom Forest - Test Data")
print("Accuracy:", accuracy_score(y_test, y_test_pred_rf))
print("Precision:", precision_score(y_test, y_test_pred_rf, average='binary'))
print("Recall:", recall_score(y_test, y_test_pred_rf, average='binary'))
print("F1 Score:", f1_score(y_test, y_test_pred_rf, average='binary'))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_test_pred_rf))
print("ROC AUC Score:", roc_auc_score(y_test, y_test_pred_rf))
print("Classification Report:\n", classification_report(y_test, y_test_pred_rf))


Random Forest - Test Data
Accuracy: 0.7433090222116726
Precision: 0.7775994285691356
Recall: 0.8917569420795406
F1 Score: 0.8307749031612207
Confusion Matrix:
 [[ 34821  55422]
 [ 23521 193777]]
ROC AUC Score: 0.638807562492847
Classification Report:
               precision    recall  f1-score   support

           0       0.60      0.39      0.47     90243
           1       0.78      0.89      0.83    217298

    accuracy                           0.74    307541
   macro avg       0.69      0.64      0.65    307541
weighted avg       0.72      0.74      0.72    307541

